version: '3.8'

services:
  frontend:
    container_name: uns-frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8502:8502"
    env_file:
      - .env
    restart: unless-stopped

  backend:
    container_name: uns-backend
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped

  pizza-uns:
      build:
        context: ./UnsSimulator
        dockerfile: Dockerfile
      image: pizza-uns:latest
      network_mode: host
      ports:
        - "8000:8000"
      env_file:
        - .env